[project]
name = "programming-iot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "numpy>=2.4.1",
    "pandas>=3.0.0",
    "xlrd>=2.0.2",
]
